version: "3.8"
networks:
  image-publisher-comms:
services:
  robster-redis:
    image: redis:7.0-alpine
    networks:
      - image-publisher-comms
    restart: unless-stopped

  robster-image-publisher:
    depends_on:
      - "robster-redis"
    networks:
      - image-publisher-comms
    build:
      context: .
      dockerfile: ./Image-Publisher.Dockerfile
    environment:
      - HOST=${HOST}
      - ROBSTER_USERNAME=${ROBSTER_USERNAME}
      - ROBSTER_PASSWORD=${ROBSTER_PASSWORD}
      - ONVIF_PORT=${ONVIF_PORT}
      - RTSP_URL=${RTSP_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_IMAGES_CHANNEL=robsterimages
      - REDIS_VIDEOS_CHANNEL=robstervideos
    restart: unless-stopped

  robster-discord-bot:
    depends_on:
      - "robster-redis"
      - "robster-image-publisher"
    networks:
      - image-publisher-comms
    build:
      context: .
      dockerfile: ./Discord-Bot.Dockerfile
    environment:
      - DISCORD_KEY=${DISCORD_KEY}
      - REDIS_URL=${REDIS_URL}
      - REDIS_IMAGES_CHANNEL=robsterimages
      - REDIS_VIDEOS_CHANNEL=robstervideos
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
    restart: unless-stopped

  robster-s3-image-storage:
    depends_on:
      - "robster-redis"
      - "robster-image-publisher"
    networks:
      - image-publisher-comms
    build:
      context: .
      dockerfile: ./Image-S3-Storage.Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - IMAGES_BUCKET_NAME=${IMAGES_BUCKET_NAME}
      - VIDEOS_BUCKET_NAME=${VIDEOS_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
    restart: unless-stopped

  robster-twitter-bot:
    depends_on:
      - "robster-redis"
      - "robster-image-publisher"
    networks:
      - image-publisher-comms
    build:
      context: .
      dockerfile: ./Twitter-Bot.Dockerfile
    environment:
      - DISCORD_KEY=${DISCORD_KEY}
      - REDIS_URL=${REDIS_URL}
      - REDIS_IMAGES_CHANNEL=robsterimages
      - REDIS_VIDEOS_CHANNEL=robstervideos
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_KEY_SECRET=${TWITTER_CONSUMER_KEY_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    restart: unless-stopped
