version: "3.8"
networks:
  robster-combined-app-comms:
services:
  robster-redis:
    image: redis:7.0-alpine
    networks:
      - robster-combined-app-comms
    restart: unless-stopped

  robster-combined-app:
    depends_on:
      - "robster-redis"
    networks:
      - robster-combined-app-comms
    build:
      context: .
      dockerfile: ./Combined.Dockerfile
    entrypoint: ./start-all.sh
    environment:
      - DISCORD_KEY=${DISCORD_KEY}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - REDIS_URL=${REDIS_URL}
      - REDIS_IMAGES_CHANNEL=robsterimages
      - REDIS_VIDEOS_CHANNEL=robstervideos
      - HOST=${HOST}
      - ROBSTER_USERNAME=${ROBSTER_USERNAME}
      - ROBSTER_PASSWORD=${ROBSTER_PASSWORD}
      - ONVIF_PORT=${ONVIF_PORT}
      - RTSP_URL=${RTSP_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - S3_REGION=${S3_REGION}
    restart: unless-stopped
